import Link from 'next/link';
import AppShell from '@/components/AppShell';
import RunActions from '@/components/RunActions';
import db from '@/lib/db';
import {usageToday} from '@/lib/model-usage';
import {modelConfigured,realContentEnabled} from '@/lib/model-config';
import {contentStatus} from '@/lib/stories';
import {formatDate} from '@/lib/reader';
import {beijingToday} from '@/lib/time';
export const dynamic='force-dynamic';
export default function Page(){
 const status=contentStatus(),usage=usageToday(),worker=db.prepare('SELECT * FROM scheduler_state WHERE id=1').get(),sources=db.prepare('SELECT * FROM sources WHERE enabled=1 ORDER BY priority,name').all(),jobs=db.prepare('SELECT * FROM job_runs ORDER BY id DESC LIMIT 12').all(),pending=Number(db.prepare("SELECT count(*) n FROM articles a LEFT JOIN summaries s ON s.article_id=a.id WHERE s.article_id IS NULL AND julianday(a.fetched_at)>=julianday('now','-7 days')").get()?.n||0);
 const visits=db.prepare("SELECT count(*) n FROM product_activity WHERE action='visit'").get()?.n||0;
 return <AppShell active="admin"><main className="single-page"><header className="page-heading"><p className="eyebrow">运行与设置</p><h1>管理</h1><p>检查内容来源、自动更新和模型用量。</p></header><div className="admin-grid"><section className="admin-panel"><h2>自动更新</h2><Link href="/admin/email" className="text-link">邮件日报设置 →</Link><dl><dt>后台进程</dt><dd>{status.running?'运行中 · 每小时检查':'当前未运行 · 等待后台任务恢复'}</dd><dt>最近检查</dt><dd>{formatDate(status.checked,true)}</dd><dt>内容更新</dt><dd>{formatDate(status.latest,true)}</dd>{worker?.last_error&&<><dt>最近状态</dt><dd>{worker.last_error}</dd></>}</dl><p className="quiet-copy">关闭网页后继续采集；电脑睡眠时暂停，恢复后补查一次。公开阅读与邮件由云端另行更新。</p></section><section className="admin-panel"><h2>模型与预算</h2><dl><dt>当前模型</dt><dd>{usage.model} · {modelConfigured()?(realContentEnabled()?'已启用':'已配置，真实材料处理暂停'):'未配置密钥'}</dd><dt>今日估算用量</dt><dd>¥{usage.cost.toFixed(4)} / ¥{usage.budget} · {usage.requests} / {usage.limit} 次请求</dd><dt>最近模型状态</dt><dd>{usage.lastStatus?.includes('429')?'服务商限流，已停止本轮处理':usage.lastStatus?.startsWith('error')?'最近请求失败，原文与已有摘要保留':usage.lastStatus||'尚无请求'}</dd></dl><p className="quiet-copy">失败请求保留预算预占，最终费用以服务商账单为准。默认每天 1 元，不自动提高现有设置。</p></section></div><section className="operation-panel"><h2>手动更新</h2><RunActions date={beijingToday()} pending={pending} modelConfigured={modelConfigured()&&realContentEnabled()}/><p className="quiet-copy">后台与手动操作共用任务锁和预算。旧档案不会自动付费重做。</p></section><section className="admin-panel" style={{marginTop:28}}><div className="section-heading"><h2>来源健康</h2><span className="quiet-copy">显示最近实际请求结果</span></div><div className="table-scroll"><table className="health-table"><thead><tr><th>来源</th><th>状态</th><th>最近成功</th><th>材料数</th><th>说明</th></tr></thead><tbody>{sources.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.last_status==='success'?'成功':s.last_status==='failed'?'暂不可用':'尚未检查'}</td><td>{formatDate(s.last_success_at,true)}</td><td>{s.last_count??'—'}</td><td>{s.last_error?String(s.last_error).slice(0,160):s.source_tier==='official'?'官方发布':'报道 / 讨论线索'}</td></tr>)}</tbody></table></div></section><section className="admin-panel" style={{marginTop:28}}><h2>任务日志</h2><div className="table-scroll"><table className="health-table"><thead><tr><th>开始</th><th>状态</th><th>新增</th><th>失败来源</th><th>结束</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>{formatDate(j.started_at,true)}</td><td>{({success:'完成',partial:'部分完成',running:'运行中',failed:'未完成'} as Record<string,string>)[j.status]||j.status}</td><td>{j.new_count}</td><td>{j.failed_count}</td><td>{formatDate(j.finished_at,true)}</td></tr>)}</tbody></table></div></section><section className="admin-panel" style={{marginTop:28}}><h2>本地使用记录</h2><p className="quiet-copy">已记录 {visits} 个访问日。关注、收藏、笔记与阅读进度只记录在本机，用于检查持续跟踪是否有用。</p><Link href="/research" className="text-link">回到我的研究 →</Link></section></main></AppShell>;
}