import Link from 'next/link';
import {regions,selectionReason,type Story} from '@/lib/stories';
import {formatDate} from '@/lib/reader';
import StoryActions from './StoryActions';
import {storySummaryStatuses} from '@/lib/summary-status';
export function EmptyState({title='暂无匹配内容',text='换一个筛选条件，或从全部材料开始阅读。',href='/search',action='查看全部材料'}:{title?:string;text?:string;href?:string;action?:string}){return <div className="empty-state"><span aria-hidden="true">◇</span><h3>{title}</h3><p>{text}</p><Link className="text-link" href={href}>{action} →</Link></div>;}
export default function StoryList({items,numbered=false,notes=false}:{items:Story[];numbered?:boolean;notes?:boolean}){
 if(!items.length)return <EmptyState/>;
 const summaryStates=storySummaryStatuses(items.filter(s=>!s.summary?.trim()).map(s=>s.representative_article_id));
 return <div className="story-list">{items.map((s,i)=><article className={'story-row '+(s.followed&&s.unread?'has-update':'')} key={s.id}>{numbered&&<span className="story-number">{String(i+1).padStart(2,'0')}</span>}<div className="story-body"><div className="story-eyebrow"><span>{regions[s.region as keyof typeof regions]||'综合'}</span>{s.source_tier==='official'&&s.is_primary?<span>官方发布</span>:<span>来源报道</span>}{s.title_zh&&<span>机器翻译</span>}{Boolean(s.followed&&s.unread)&&<span className="new-badge">{s.last_read_update?'有新进展':'未读'}</span>}</div><h2><Link href={'/stories/'+s.id}>{s.title}</Link></h2><p className="story-summary">{s.summary?<><span className="inline-label">模型摘要</span>{s.summary.length>130?s.summary.slice(0,130)+'…':s.summary}</>:<><span className="inline-label">{summaryStates.get(s.representative_article_id)?.label||'待摘要'}</span>{summaryStates.get(s.representative_article_id)?.message||'材料已保存，可先核对原始发布。'}</>}</p><div className="story-meta"><span>{s.publisher||'来源待补'}</span><time>{s.published_at?formatDate(s.published_at):'发布日期待核 · 收录 '+formatDate(s.fetched_at)}</time><Link href={'/articles/'+s.representative_article_id}>核对材料 ↗</Link></div>{notes&&s.note&&<blockquote className="saved-note">{s.note}</blockquote>}</div><div className="story-context"><p><span>关注理由</span>{selectionReason(s)}</p><StoryActions id={s.id} followed={Boolean(s.followed)}/></div></article>)}</div>;
}
export function StoryRail({items,empty='暂无材料'}:{items:Story[];empty?:string}){return <div className="rail-list">{items.length?items.map(s=><Link className="rail-item" key={s.id} href={'/stories/'+s.id}><span className="region-badge">{regions[s.region as keyof typeof regions]||'综合'}</span><div><h3>{s.title}</h3><p>{formatDate(s.published_at||s.fetched_at)}{s.followed?(s.unread?' · 有新进展':' · 已读'):''}</p></div></Link>):<p className="quiet-copy">{empty}</p>}</div>;}
