'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export default function StoryActions({id,followed=false,saved=false,note='',revision=0,full=false}:{id:string;followed?:boolean;saved?:boolean;note?:string;revision?:number;full?:boolean}){
 const router=useRouter(),[following,setFollowing]=useState(followed),[keeping,setKeeping]=useState(saved),[draft,setDraft]=useState(note),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
 async function commit(action:string,value:boolean|string|number){setBusy(true);setMessage('');setError(false);try{const r=await fetch('/api/stories/'+id+'/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,value})});const j=await r.json();if(!r.ok)throw new Error(j.error||'保存失败');if(action==='follow')setFollowing(Boolean(value));if(action==='save')setKeeping(Boolean(value));setMessage(action==='note'?'笔记已保存':action==='read'?'本次进展已读':action==='follow'?(value?'已关注，后续进展将在我的研究中提示':'已取消关注'):(value?'已收藏':'已取消收藏，笔记保留'));router.refresh();}catch(e){setError(true);setMessage(e instanceof Error?e.message:'保存失败，请重试');}finally{setBusy(false);}}
 return <div className={'story-actions '+(full?'full':'compact')}><div className="action-buttons"><button className={following?'follow-button selected':'follow-button'} aria-pressed={following} disabled={busy} onClick={()=>void commit('follow',!following)}>{following?'✓ 已关注':'＋ 关注'}</button>{full&&<><button className="secondary-button" aria-pressed={keeping} disabled={busy} onClick={()=>void commit('save',!keeping)}>{keeping?'✓ 已收藏':'收藏事件'}</button><button className="text-button" disabled={busy} onClick={()=>void commit('read',revision)}>标记本次已读</button></>}</div>
 {full&&<form className="note-editor" onSubmit={e=>{e.preventDefault();void commit('note',draft);}}><label htmlFor={'story-note-'+id}>我的研究笔记</label><textarea id={'story-note-'+id} value={draft} onChange={e=>setDraft(e.target.value)} rows={5} maxLength={4000} placeholder="这改变了什么？依据是什么？哪些证据会让我改变看法？"/><div className="note-actions"><small>仅保存在本机 · {draft.length}/4000</small><button className="primary-button" disabled={busy} type="submit">{busy?'保存中…':'保存笔记'}</button></div></form>}
 <span className={'save-message '+(error?'error-text':'')} role={error?'alert':'status'}>{message}</span></div>;
}