import type {PublicArticle,PublicEdition,PublicEvent,PublicIssue} from './public-edition';
import {regions,sectors,themes} from './story-classification';
import {overviewWindow} from './overview-window';
export const escapeHtml=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const h=escapeHtml;
export function day(v:string|null,time=false){return v&&Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',...(time&&/(?:T|\s)\d{2}:\d{2}/.test(v)?{hour:'2-digit',minute:'2-digit'}:{})}).format(new Date(v)):'日期未标注';}
function paragraphs(v:string){return v.split(/\n\s*\n/).map(p=>'<p>'+h(p).replace(/\n/g,'<br>')+'</p>').join('');}
function short(v:string,n=115){return v.length>n?v.slice(0,n)+'…':v;}
function heading(title:string,extra=''){return '<header class="page-heading">'+(extra?'<p class="eyebrow">'+h(extra)+'</p>':'')+'<h1>'+h(title)+'</h1></header>';}
function preferences(){return '<div class="settings-panel"><label>外观<select data-preference="theme"><option value="system">跟随系统</option><option value="light">日间</option><option value="dark">夜间</option></select></label><label>正文字号<select data-preference="size"><option value="standard">标准 · 16px</option><option value="large">大字 · 18px</option></select></label><label>阅读宽度<select data-preference="width"><option value="standard">标准</option><option value="wide">宽幅</option></select></label></div>';}
const sourceLabel=(a:PublicArticle)=>'<span class="source-label">'+h(a.sourceRole)+'</span>';
const meta=(a:PublicArticle)=>sourceLabel(a)+' <span>'+h(a.publisher)+' · '+(a.publishedAt?'发布 '+h(day(a.publishedAt)):'发布日期未标注')+'</span>';
function card(a:PublicArticle){return '<article class="story-row"><div class="story-body"><div class="story-eyebrow"><span>'+h(a.topicLabel)+'</span><span>'+h(sectors[a.sector as keyof typeof sectors]||'市场观察')+'</span>'+sourceLabel(a)+'</div><h2><a href="/articles/'+a.id+'/">'+h(a.title)+'</a></h2><p class="story-summary"><span class="inline-label">'+(a.summary?'模型摘要':'原文摘录')+'</span>'+h(a.summary||a.factExcerpt||'摘要待补；可核对来源陈述与原始发布。')+'</p><div class="story-meta"><span>'+h(a.publisher)+' · '+(a.publishedAt?'发布 '+h(day(a.publishedAt)):'发布日期未标注')+'</span><a href="/events/'+a.eventId+'/">关联事件 →</a></div></div></article>';}
function cards(rows:PublicArticle[]){return '<div class="story-list">'+rows.map(card).join('')+'</div>';}
function empty(message:string){return '<div class="empty-state"><h2>暂无可发布材料</h2><p>'+h(message)+'</p><a href="/search/" class="text-link">查看资料库 →</a></div>';}
function judgment(a:PublicArticle,index=0){
 const j=a.judgment;if(!j)return '<p class="quality-note">材料待核对：暂未形成可追溯的完整判断。</p>';
 return '<article class="digest-thesis"><div class="digest-thesis-heading"><span class="digest-index" aria-hidden="true">'+String(index+1).padStart(2,'0')+'</span><div><p class="eyebrow">模型推论 · '+(j.horizon==='short'?'短期':j.horizon==='long'?'长期':'背景观察')+'</p><h3>'+h(j.thesis)+'</h3></div></div>'+
 (j.direction?'<p class="trend-kicker"><span class="direction '+h(j.direction)+'">'+(j.direction==='bullish'?'条件偏多':j.direction==='bearish'?'条件偏空':'中性观察')+'</span><span>'+h(j.asset)+'</span></p>':'')+
 '<div class="digest-mechanism">'+paragraphs(j.mechanism)+'</div><dl class="digest-checks"><div><dt>成立条件</dt><dd>'+h(j.conditions||'原模型未单列成立条件；需结合传导说明核对，不视为无条件成立。')+'</dd></div><div><dt>反向检验</dt><dd>'+h(j.counterpoint)+'</dd></div><div><dt>继续跟踪 · 下次看什么</dt><dd>'+h(j.watch)+'</dd></div></dl><details class="digest-evidence"><summary>核对生成依据 · '+h(a.publisher)+'</summary><blockquote>'+h(j.evidence)+'</blockquote><p>引用来自材料 '+a.id+'。'+(a.generatedAt?'生成 '+h(day(a.generatedAt,true)):'原生成时间未保留')+' · '+(a.basisKind==='generated'?'已绑定原文指纹':'历史输出经本轮规则复核，原模型与提示版本未保留')+'</p><a href="/articles/'+a.id+'/" class="text-link">材料、摘要与原文 →</a></details></article>';
}
export function createPublicReader(edition:PublicEdition,logo:string,siteOrigin="",runtime:{mode?:'cloud'|'snapshot';checkedAt?:string|null;updateStatus?:string|null}={}){
 const byId=new Map(edition.articles.map(a=>[a.id,a]));
 const sectorsList=Object.entries(sectors).filter(([key])=>!['macro','general'].includes(key));
 const snapshot=day(edition.snapshotAt,true);
 function shell(title:string,active:string,body:string,view='',canonicalPath=''){
  const canonical=siteOrigin&&canonicalPath?siteOrigin+canonicalPath:'';
  const social=canonical?'<link rel="canonical" href="'+h(canonical)+'"><meta property="og:type" content="website"><meta property="og:site_name" content="财经观点台账"><meta property="og:title" content="'+h(title+' · 财经观点台账')+'"><meta property="og:description" content="宏观与产业研究的公开资料快照：识别变化、核对来源、检验条件与反证。"><meta property="og:url" content="'+h(canonical)+'"><meta name="twitter:card" content="summary">':'';
  const indexing=siteOrigin&&canonicalPath!=='/'&&canonicalPath!=='/about/'?'<meta name="robots" content="noindex,follow">':'';
  const navs=[['today','/','今日总览'],['macro','/macro/','宏观趋势'],['industry','/industry/','产业前沿'],['daily','/daily/','财经日报'],['search','/search/','资料库'],['about','/about/','阅读说明']];
  const nav=navs.map(([key,url,text])=>'<a class="nav-link '+(key===active?'active':'')+'" href="'+url+'"'+(key===active?' aria-current="page"':'')+'>'+text+'</a>'+(key==='industry'?'<div class="nav-subitems">'+sectorsList.map(([key,text])=>'<a href="/industry/?sector='+key+'">'+h(text)+'</a>').join('')+'</div>':'')).join('');
  const mobile=[['today','/','首页'],['macro','/macro/','宏观'],['industry','/industry/','产业'],['daily','/daily/','日报'],['search','/search/','资料库']].map(([key,url,text])=>'<a href="'+url+'"'+(key===active?' class="active" aria-current="page"':'')+'>'+text+'</a>').join('');
  return '<!doctype html><html lang="zh-CN" data-theme="system"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><link rel="icon" type="image/webp" href="/reader/cutout-4-faa830732ac5.webp"><title>'+h(title)+' · 财经观点台账</title><meta name="description" content="宏观与产业研究的公开资料快照：识别变化、核对来源、检验条件与反证。">'+indexing+social+'<script src="/assets/filter-init.js"></script><link rel="stylesheet" href="/assets/reader.css"><script src="/assets/reader.js" defer></script></head><body><div class="app-shell"><a class="skip-link" href="#page-content">跳到正文</a><aside class="side-nav"><a href="/" class="brand-mark"><span class="brand-symbol" aria-hidden="true">'+logo+'</span><span><strong>财经观点台账</strong><small>宏观与产业 · 公开阅读</small></span></a><nav class="side-nav-links" aria-label="主导航">'+nav+'</nav><div class="side-nav-foot"><details class="reading-settings"><summary class="nav-link">阅读设置</summary>'+preferences()+'</details></div></aside><div class="app-stage"><header class="top-bar"><a class="mobile-brand" href="/">财经观点台账</a><form action="/search/" class="global-search" role="search"><input name="q" aria-label="搜索公开资料" placeholder="搜索主题、事件或来源…" maxlength="120"><button type="submit">搜索</button></form><div class="top-actions"><a href="/settings/">阅读设置</a><a href="/about/">阅读说明</a></div></header><div id="page-content" tabindex="-1"'+(view?' data-view="'+view+'"':'')+'>'+body+'</div><footer class="page-footer"><span>财经观点台账 · 公开阅读</span>'+(active==='today'?'<span>发布 '+h(snapshot)+'</span>':'<div class="footer-freshness" data-content-updated-at="'+h(edition.contentUpdatedAt||'')+'"><span data-freshness-status>已保存的资料快照</span><span>最近收录 <time>'+h(day(edition.contentUpdatedAt,true))+'</time></span><a href="/about/">阅读说明</a></div>')+'</footer></div><nav class="mobile-nav" aria-label="移动端导航">'+mobile+'</nav></div></body></html>';
 }
 function notice(){return '<section class="edition-status" aria-label="资料时效" data-content-updated-at="'+h(edition.contentUpdatedAt||'')+'"><div class="freshness"><strong data-freshness-status>已保存的资料快照</strong><span>最近收录 <time>'+h(day(edition.contentUpdatedAt,true))+'</time></span>'+(runtime.checkedAt?'<span>来源检查 <time>'+h(day(runtime.checkedAt,true))+'</time> · '+(runtime.updateStatus==='success'?'完成':runtime.updateStatus==='partial'?'部分来源不可用':'来源检查失败')+'</span>':'')+'<a href="/about/">更新说明</a></div><p class="public-snapshot-note" data-freshness-message>'+(runtime.mode==='cloud'?'来源检查与资料发布日期分别记录。':'本地整理后定期发布，按原始发布日期阅读。')+'</p></section>';}
 function eventLead(event:PublicEvent){const members=event.articleIds.map(id=>byId.get(id));return members.find(a=>a?.judgment?.conditions&&a.judgment.horizon!=='knowledge')||members.find(a=>a?.judgment?.conditions)||byId.get(event.representativeArticleId)!;}
 const isKeyJudgment=(event:PublicEvent)=>{const j=eventLead(event).judgment;return Boolean(j?.conditions&&j.horizon!=='knowledge');};
 function eventCard(event:PublicEvent,index:number){
  const a=eventLead(event),j=a.judgment?.conditions?a.judgment:null;
  return '<article class="key-change"><div class="key-change-top"><span class="change-index" aria-hidden="true">'+String(index+1).padStart(2,'0')+'</span><div><p class="eyebrow">'+h(a.topicLabel)+' · '+h(day(event.latestAt))+'</p><h2><a href="/events/'+event.id+'/">'+h(event.title)+'</a></h2></div></div><dl class="change-reading"><div><dt>发生了什么 <span>'+(a.summary?'模型摘要':'原文摘录')+'</span></dt><dd>'+h(short(a.summary||a.factExcerpt))+'</dd></div><div><dt>可能影响什么 <span>模型推论</span></dt><dd>'+h(j?short(j.thesis):'材料待核对，暂不推定市场方向。')+'</dd></div><div><dt>成立条件</dt><dd>'+h(j?short(j.conditions||'',100):'判断条件待核对。')+'</dd></div><div><dt>下次看什么验证</dt><dd>'+h(j?short(j.watch,85):'先核对原始发布与后续确认材料。')+'</dd></div></dl><div class="story-meta">'+meta(a)+'<span>来源独立性待核</span><a href="/events/'+event.id+'/">条件、反证与原文</a></div></article>';
 }
 function home(){
  const macroEvents=edition.events.filter(e=>e.sector==='macro'&&byId.get(e.representativeArticleId)!.sourceTier!=='community');
  const window=overviewWindow(macroEvents.map(e=>({...e,published_at:e.latestAt,latest_at:e.latestAt||''})),Date.parse(edition.snapshotAt));
  const datedRecent=macroEvents.filter(e=>e.latestAt&&Date.parse(e.latestAt)<=Date.parse(edition.snapshotAt)&&Date.parse(e.latestAt)>=Date.parse(edition.snapshotAt)-72*3600000);
  const current=datedRecent.length?datedRecent:(window.items as Array<PublicEvent&{published_at:string|null;latest_at:string}>);
  const rank=(e:PublicEvent)=>{const a=byId.get(e.representativeArticleId)!;return Number(a.sourceTier==='official')*8+Number(!!a.judgment?.conditions)*3+Number(!!a.judgment)*2+Number(e.region==='china');};
  const ranked=current.filter(isKeyJudgment).sort((a,b)=>rank(b)-rank(a)||Date.parse(b.latestAt||'')-Date.parse(a.latestAt||''));
  const selected:PublicEvent[]=[];const china=ranked.find(e=>e.region==='china');if(china)selected.push(china);
  for(const region of ['us','europe','japan','global']){const e=ranked.find(e=>e.region===region);if(e&&selected.length<3)selected.push(e);}
  for(const e of ranked)if(selected.length<3&&!selected.some(s=>s.id===e.id))selected.push(e);
  const ids=new Set(selected.map(e=>e.id));
   const leadCandidates=current.filter(e=>!ids.has(e.id)).sort((a,b)=>Number(eventLead(b).sourceRole==='官方发布')-Number(eventLead(a).sourceRole==='官方发布')||Date.parse(b.latestAt||'')-Date.parse(a.latestAt||''));
   const unreviewed:PublicEvent[]=[],usedTitles=new Set<string>(),usedRegions=new Set<string>(),usedPublishers=new Set<string>();
   const addLead=(e:PublicEvent)=>{const title=e.title.replace(/\s+/g,'').toLocaleLowerCase();if(unreviewed.length>=5||usedTitles.has(title))return;unreviewed.push(e);usedTitles.add(title);usedRegions.add(e.region);usedPublishers.add(eventLead(e).publisher);};
   for(const e of leadCandidates)if(!usedRegions.has(e.region))addLead(e);
   for(const e of leadCandidates)if(!usedPublishers.has(eventLead(e).publisher))addLead(e);
   for(const e of leadCandidates)addLead(e);
  const backgroundCandidates=macroEvents.filter(e=>!ids.has(e.id)&&!current.some(c=>c.id===e.id)&&eventLead(e).sourceRole==='官方发布');
   const backgrounds:PublicEvent[]=[],backgroundPublishers=new Set<string>();
   for(const e of backgroundCandidates){const publisher=eventLead(e).publisher;if(backgroundPublishers.has(publisher))continue;backgrounds.push(e);backgroundPublishers.add(publisher);if(backgrounds.length>=4)break;}
  const label=datedRecent.length?'近 72 小时发布 · 截至 '+day(edition.snapshotAt):window.label;
  const materialLeads=unreviewed.map((e,i)=>{const a=eventLead(e);return '<article class="story-row home-material"><span class="story-number" aria-hidden="true">'+String(i+1).padStart(2,'0')+'</span><div class="story-body"><div class="story-eyebrow">'+sourceLabel(a)+'<span>'+h(a.topicLabel)+'</span></div><h2><a href="/events/'+e.id+'/">'+h(e.title)+'</a></h2><p class="story-summary"><span class="inline-label">'+(a.summary?'模型摘要':'原文摘录')+'</span>'+h(short(a.summary||a.factExcerpt,150))+'</p><div class="story-meta"><span>'+h(a.publisher)+'</span><time>发布 '+h(day(e.latestAt))+'</time><a href="/articles/'+a.id+'/">核对材料</a></div></div></article>';}).join('');
  const latestDay=current.map(e=>e.latestAt).filter((v):v is string=>Boolean(v)).sort((a,b)=>Date.parse(b)-Date.parse(a))[0];
  const masthead='<header class="page-heading overview-masthead"><p class="eyebrow">宏观与产业 · 公开阅读</p><div class="heading-line"><h1>本期阅读总览</h1><span class="edition-date">'+h(latestDay?day(latestDay):'发布日期待核')+'</span></div></header>';
  const metrics='<nav class="edition-metrics" aria-label="本期资料覆盖"><a href="/search/"><strong>'+edition.articles.length+'</strong><span>公开材料</span></a><a href="/macro/"><strong>'+edition.events.length+'</strong><span>归并事件</span></a><a href="/daily/"><strong>'+edition.issues.length+'</strong><span>归档日报</span></a></nav>';
  return shell('本期阅读总览','today','<main class="reader-layout"><div class="primary-column">'+masthead+notice()+metrics+
   '<section class="home-materials" aria-labelledby="material-leads-title"><div class="section-heading"><h2 id="material-leads-title">同期材料线索</h2><a class="text-link" href="/macro/">查看宏观材料</a></div><p class="section-note">'+h(label)+'</p>'+(materialLeads?'<div class="story-list">'+materialLeads+'</div>':empty('本期其他材料可在资料库核对。'))+'</section>'+
   (selected.length?'<section class="home-judgments" aria-labelledby="key-changes-title"><div class="section-heading"><h2 id="key-changes-title">条件判断</h2><span class="quiet-copy">模型推论</span></div>'+selected.map(eventCard).join('')+'</section>':'')+'</div><aside class="context-rail"><section><div class="section-heading"><h2>财经日报</h2></div>'+(edition.issues[0]?'<p class="issue-date">'+h(edition.issues[0].date)+'</p><p class="quiet-copy">按发布日期阅读当期材料</p><a class="text-link" href="/daily/">阅读完整日报</a>':'<p>暂无本期日报。</p>')+'</section><section><div class="section-heading"><h2>持续背景</h2></div><p class="quiet-copy">较早发布的官方材料。</p>'+backgrounds.map(e=>'<article class="rail-item"><p class="eyebrow">'+h(day(e.latestAt))+'</p><h3><a href="/events/'+e.id+'/">'+h(e.title)+'</a></h3></article>').join('')+'</section></aside></main>','','/');
 }
 function filterPage(kind:'search'|'macro'|'industry'){
  const initial=edition.articles.filter(a=>kind==='macro'?a.sector==='macro':kind==='industry'?a.sector==='ai':true);
  const regionOptions=kind==='industry'?[['','全部地区'],['china','中国'],['us','美国'],['global','全球（全部地区）']]:[['','全部地区'],...Object.entries(regions)];
  const controls='<form class="public-filter-form" data-filter-form><div class="filter-panel"><label>关键词<input name="q" maxlength="120" placeholder="标题、摘要或来源"></label><label>地区<select name="region">'+regionOptions.map(([k,v])=>'<option value="'+k+'">'+h(v)+'</option>').join('')+'</select></label>'+
   (kind==='macro'?'<label>主题<select name="theme"><option value="">全部主题</option>'+Object.entries(themes).map(([k,v])=>'<option value="'+k+'">'+h(v)+'</option>').join('')+'</select></label>':'<label>分类<select name="sector"><option value="">'+(kind==='industry'?'全部产业':'全部分类')+'</option>'+Object.entries(sectors).filter(([k])=>kind==='search'||!['macro','general'].includes(k)).map(([k,v])=>'<option value="'+k+'"'+(kind==='industry'&&k==='ai'?' selected':'')+'>'+h(v)+'</option>').join('')+'</select></label>')+
   '<label>排序<select name="sort"><option value="date">发布日期</option><option value="relevance">相关性</option></select></label><button type="submit" class="primary-button">筛选</button></div></form>';
  const title=kind==='search'?'资料库与搜索':kind==='macro'?'宏观趋势':'产业前沿';
  return shell(title,kind,'<main class="single-page library-page">'+heading(title)+controls+'<div class="library-meta"><span data-result-count>'+initial.length+' 条公开材料</span></div><section data-public-results data-initial-results aria-label="搜索结果">'+cards(initial.slice(0,20))+'</section><div class="public-load-more"><button type="button" class="secondary-button" data-load-more hidden>再显示 20 条</button><p class="quiet-copy" data-result-status role="status"></p></div><noscript><p>筛选需要启用 JavaScript。默认材料列表仍可阅读，查询参数未应用。</p></noscript></main>',kind,'/'+kind+'/');
 }
 function issueBody(issue:PublicIssue){
  const materials=issue.articleIds.map(id=>byId.get(id)!).filter(Boolean);
  const representative=new Map<string,PublicArticle>();
  for(const a of materials){const old=representative.get(a.eventId);if(!old||(!old.judgment&&a.judgment))representative.set(a.eventId,a);}
  const rank=(a:PublicArticle)=>Number(a.sourceTier==='official')*4+Number(Boolean(a.judgment?.conditions))*3+Number(a.judgment?.horizon!=='knowledge')*2+Number(a.sector==='macro');
  const points=[...representative.values()].filter(a=>a.judgment).sort((a,b)=>rank(b)-rank(a)||Date.parse(b.publishedAt||'')-Date.parse(a.publishedAt||'')).slice(0,8);
  const brief=(points.length?points:[...representative.values()]).slice(0,3);
  const dates='<nav class="issue-navigation" aria-label="日报日期"><span>近期日报</span>'+edition.issues.slice(0,5).map(d=>'<a href="/daily/'+d.date+'/"'+(d.date===issue.date?' class="active" aria-current="page"':'')+'>'+h(d.date.slice(5))+'</a>').join('')+'</nav>'+
   (edition.issues.length>5?'<details class="issue-archive"><summary>更早归档</summary><div>'+edition.issues.slice(5).map(d=>'<a href="/daily/'+d.date+'/">'+h(d.date)+'</a>').join('')+'</div></details>':'');
  return '<main class="single-page daily-page">'+heading(issue.date+' 财经日报','按收录日期归档')+
   '<section class="issue-brief" aria-labelledby="issue-brief-title"><div class="section-heading"><h2 id="issue-brief-title">本期要点</h2><span class="quiet-copy">'+(points.length?(points.every(a=>Boolean(a.judgment?.conditions))?'条件性模型判断':'模型判断 · 部分成立条件待补'):'来源摘要 · 尚无完整判断')+'</span></div><ol>'+brief.map(a=>'<li><h3><a href="#'+(a.judgment?'point-'+a.id:'digest-references')+'">'+h(short(a.judgment?.thesis||a.summary||a.factExcerpt,85))+'</a></h3><p>'+h(short(a.judgment?.watch||a.topicLabel,70))+'</p></li>').join('')+'</ol></section>'+dates+'<div class="daily-reading-grid"><article class="daily-report-sheet"><section id="digest-theses"><div class="section-heading"><h2>本期判断</h2></div>'+(points.length?points.map((a,i)=>'<section id="point-'+a.id+'">'+judgment(a,i)+'</section>').join(''):'<p class="quality-note">材料待核对：暂无完整依据的判断，不以材料数量补足结论。</p>')+'</section></article><aside id="digest-references" class="reference-panel" data-reference-section><div class="section-heading"><h2>参考资料</h2></div><label class="reference-search">按标题或来源检索<input data-reference-filter placeholder="输入关键词" aria-controls="reference-list"></label><p class="quiet-copy" data-reference-count role="status">'+materials.length+' 条参考资料</p><ol id="reference-list" class="digest-reference-list">'+materials.map(a=>'<li data-reference-row><a href="/articles/'+a.id+'/">'+h(a.title)+'</a><p>'+meta(a)+'</p></li>').join('')+'</ol><a href="/search/?date='+issue.date+'" class="text-link">在资料库检索本期 →</a></aside></div></main>';
 }
 function articleBody(a:PublicArticle){
  const summary=a.summary?'<section class="reading-section evidence-section"><h2>内容摘要</h2><p class="eyebrow">模型摘要</p>'+paragraphs(a.summary)+'</section>':'';
  const reasoning=a.judgment?'<section class="reading-section evidence-section"><h2>模型推论与反向检验</h2>'+judgment(a)+'</section>':'';
  return '<main class="reading-layout"><article class="reading-main"><p class="breadcrumb"><a href="/search/">资料库</a> / <a href="/events/'+a.eventId+'/">关联事件</a></p><header class="article-heading"><p class="eyebrow">'+h(a.topicLabel)+' · '+h(sectors[a.sector as keyof typeof sectors])+'</p><h1>'+h(a.title)+'</h1>'+(a.originalTitle?'<p class="original-title" lang="en">原标题：'+h(a.originalTitle)+'</p>':'')+'<div class="reader-meta">'+meta(a)+'</div></header><section class="reading-section evidence-section"><h2>来源原本声称什么</h2><p class="eyebrow">'+h(a.sourceRole)+' · 原文摘录</p>'+(a.factExcerpt?'<blockquote>'+h(a.factExcerpt)+'</blockquote>':'<p>请直接核对原始发布。</p>')+'<a href="'+h(a.url)+'" target="_blank" rel="noreferrer" class="text-link">阅读完整原文 ↗</a></section>'+summary+reasoning+'</article><aside class="reading-aside"><section><h2>来源与依据</h2><dl class="source-audit"><dt>材料类型</dt><dd>'+h(a.sourceRole)+'</dd><dt>发布者</dt><dd>'+h(a.publisher)+'</dd><dt>原始发布日期</dt><dd>'+h(day(a.publishedAt,true))+'</dd><dt>收录时间</dt><dd>'+h(day(a.fetchedAt,true))+'</dd>'+(a.generatedAt?'<dt>生成时间</dt><dd>'+h(day(a.generatedAt,true))+'</dd>':'')+'<dt>依据标识</dt><dd><code>'+h(a.basisFingerprint.slice(0,12))+'</code></dd></dl><a class="text-link" href="/about/">来源与阅读说明 →</a><a class="text-link" href="/events/'+a.eventId+'/">事件报道与时间线 →</a></section></aside></main>';
 }
 function eventBody(event:PublicEvent){
  const reports=event.articleIds.map(id=>byId.get(id)!).filter(Boolean).sort((a,b)=>Date.parse(b.publishedAt||'')-Date.parse(a.publishedAt||''));
  const a=byId.get(event.representativeArticleId)!,j=reports.find(a=>a.judgment);
  const category=event.sector==='macro'?'/macro/':event.sector==='general'?'/search/?sector=general':'/industry/?sector='+event.sector;
  return '<main class="reading-layout"><article class="reading-main"><p class="breadcrumb"><a href="'+category+'">返回分类</a> / 事件</p><header class="article-heading"><p class="eyebrow">'+h(a.topicLabel)+' · 事件归并视图</p><h1>'+h(event.title)+'</h1><div class="reader-meta"><span>最近发布 '+h(day(event.latestAt))+'</span>'+(reports.length>1?'<span>'+reports.length+' 篇关联材料</span>':'')+'</div></header><section class="reading-section evidence-section"><h2>发生了什么</h2><p class="eyebrow">'+(a.summary?'模型摘要 · 依据 ':'原文摘录 · ')+h(a.sourceRole)+' · '+h(a.publisher)+'</p>'+paragraphs(a.summary||a.factExcerpt)+'</section>'+(j?'<section class="reading-section evidence-section"><h2>可能如何传导与反向检验</h2>'+judgment(j)+'</section>':'')+'<section class="reading-section"><h2>后续报道与原始依据</h2>'+(reports.length>1?'<p class="quality-note">'+(event.independence==='shared_origin'?'关联报道存在同源转载，不能作为独立佐证。':'来源独立性待核验，关联报道不等于独立证据。')+'</p>':'')+'<div class="timeline">'+reports.map(r=>'<article class="timeline-item"><time>'+(r.publishedAt?'原始发布 '+h(day(r.publishedAt,true)):'发布日期未标注 · 收录 '+h(day(r.fetchedAt,true)))+'</time><h3><a href="/articles/'+r.id+'/">'+h(r.title)+'</a></h3><p class="story-meta">'+meta(r)+'</p><a class="text-link" href="'+h(r.url)+'" target="_blank" rel="noreferrer">核对原文 ↗</a></article>').join('')+'</div></section></article><aside class="reading-aside"><h2>原始来源</h2><p>'+h(a.publisher)+'</p><p class="quiet-copy">'+h(a.sourceRole)+'</p><a href="'+h(a.url)+'" target="_blank" rel="noreferrer" class="text-link">核对原始发布 ↗</a><p><a href="/about/" class="text-link">来源与归并说明 →</a></p></aside></main>';
 }
 function about(){
  return '<main class="single-page">'+heading('阅读与更新说明','公开快照 · 质量与来源边界')+'<section class="reading-section"><h2>更新方式</h2><p>快照截止 '+h(snapshot)+'；最近收录 '+h(day(edition.contentUpdatedAt,true))+'。'+(runtime.mode==='cloud'?'官方来源检查结果由云端保存。资料发布日期、最近收录与来源检查时间分别记录；没有新增材料时不会改写收录时间。新增材料通过正文与日期检查后展示原文短摘录和链接；模型判断保留已复核版本，不自动追加付费调用。'+(runtime.checkedAt?'最近检查 '+h(day(runtime.checkedAt,true))+'，'+(runtime.updateStatus==='success'?'来源检查完成。':runtime.updateStatus==='partial'?'部分来源暂不可用。':'本次来源检查失败，保留已有资料。'):'首次来源检查尚未完成。'):'本地整理后定期发布；本期不提供实时行情或自动付费模型处理。')+'</p></section><section class="reading-section"><h2>质量门槛与复核</h2><p>正文提取失败、栏目列表、标题与正文/摘要错位、分类无材料依据或生成指纹变化，进入内部复核队列。规则结合页面结构、正文覆盖和依据指纹，不能替代事实核验与跨语言人工抽样。事件按日期、政策动作、关键数值与正文覆盖核对；相近主题和不确定关系不会自动合并。</p><p>缺少实质正文的材料不生成研究判断；历史生成版本未保留时明确说明。完整方向判断保留具体材料、引用、成立条件、反证和跟踪线索；历史判断如缺少单列条件会明确标注，且不进入首页重点。</p></section><section class="reading-section"><h2>来源类型与使用权</h2><p>官方发布、媒体转述、社区观点使用文字标签区分。官方发布可能包含第三方转载；来源数量不等于独立证据数量。</p><p>本产品的中文译题、摘要和推论由本产品生成，不是原发布机构的译文或背书。原始资料可在各来源网站免费核对。</p><p>商业化前仍需逐项审查媒体授权、转载权利人、第三方图表、翻译和数据库/API条款。证券时报与东方财富存在明确授权限制；官方网站也不代表所有材料可自由商用。本轮未取得新增授权。</p><ul><li><a href="https://www.stcn.com/public/copyright.html">证券时报版权声明</a></li><li><a href="https://about.eastmoney.com/home/legal">东方财富法律声明</a></li><li><a href="https://www.ecb.europa.eu/services/using-our-site/disclaimer/html/index.en.html">ECB使用与版权条件</a></li><li><a href="https://ec.europa.eu/eurostat/help/copyright-notice">Eurostat版权及数据例外</a></li></ul></section><section class="reading-section"><h2>个人数据</h2><p>手动导入、笔记、收藏、关注、密钥与处理日志均不进入公开构建。阅读设置只存在当前浏览器；本轮不提供登录、支付或订阅。</p></section></main>';
 }
 return {shell,home,filterPage,issueBody,articleBody,eventBody,about,settings:()=>'<main class="single-page">'+heading('阅读设置')+'<section class="operation-panel public-full-settings"><p>设置仅保存于当前浏览器。</p>'+preferences()+'</section></main>',review:()=>'<main class="single-page">'+heading('材料待核对')+'<p>该材料尚未满足本期正文、摘要与分类核验条件，暂不公开摘要或研究判断。原始记录和复核依据保留在内部台账。</p><a href="/search/" class="text-link">阅读已通过检查的材料 →</a></main>',empty};
}
